trigger: none

parameters:
- name: reactNativeVersion
  displayName: React Native Version
  type: string

variables:
  - template: variables/vs2019.yml

pool:
  vmImage: $(VmImage)

steps:
  - template: templates/prepare-env.yml
    parameters:
      yarnBuildCmd: build

  - script: git checkout -b integrate-${{ parameters.reactNativeVersion }} origin/master
    displayName: Create a new branch

  - script: yarn integrate-rn ${{ parameters.reactNativeVersion }} --reportPath integraton-report.md
    displayName: Run Integration Script
